# -*- coding: utf-8 -*-
"""EmailAgent1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14UJoLjeNnjTwWl7EBMiWLK5xFdvZoYcF
"""

from __future__ import annotations
import json, re, sqlite3, uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Literal, TypedDict
import requests
from langgraph.graph import END, START, StateGraph

try:
    from google.colab import userdata
    def _secret(key, default=""):
        try:
            return (userdata.get(key) or default).strip()
        except Exception:
            return default
except Exception:
    import os
    def _secret(key, default=""):
        return (os.environ.get(key) or default).strip()

# ---------------- config ----------------
GROQ_API_KEY   = _secret("GROQ_API_KEY")
GROQ_MODEL     = "llama-3.3-70b-versatile"
GROQ_API_URL   = "https://api.groq.com/openai/v1/chat/completions"

RESEND_API_KEY  = _secret("RESEND_API_KEY")
RESEND_FROM_EMAIL  = "onboarding@resend.dev"   # Resend's shared test domain
RESEND_SENDER_NAME = "SDR Team"
RESEND_API_URL     = "https://api.resend.com/emails"

# ── TEST-MODE OVERRIDE ──────────────────────────────────────────────────────
# Resend's free tier only allows sending to your own verified address.
# Set TEST_RECIPIENT to your address to receive all emails during dev;
# set it to "" (empty string) to use the real lead email (requires domain).
TEST_RECIPIENT = _secret("TEST_RECIPIENT", "sohampatjoshi2005@gmail.com")
# ────────────────────────────────────────────────────────────────────────────

SDR_OUTREACH_PROVIDER = "resend" if RESEND_API_KEY else "dry_run"
SDR_DATABASE_PATH     = "/content/sdr_pipeline.db"
CONFIDENCE_THRESHOLD  = 0.45


def _utc_now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------- llm client ----------------
class LLMUnavailable(Exception):
    pass


def llm_complete(system_prompt, user_prompt, temperature=0.2, max_tokens=800):
    if not GROQ_API_KEY:
        raise LLMUnavailable("No GROQ_API_KEY configured.")
    headers = {"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"}
    payload  = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        "temperature": temperature,
        "max_tokens":  max_tokens,
    }
    try:
        resp = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=30)
    except Exception as exc:
        raise LLMUnavailable(str(exc)) from exc
    if not resp.ok:
        raise LLMUnavailable(f"Groq error {resp.status_code}: {resp.text}")
    try:
        return resp.json()["choices"][0]["message"]["content"].strip()
    except Exception as exc:
        raise LLMUnavailable(f"Unexpected Groq response shape: {exc}") from exc


# ---------------- email provider ----------------
def send_email(to_email: str, subject: str, body: str) -> dict:
    """
    Send an email.

    In test mode (TEST_RECIPIENT is set), all emails are redirected to
    TEST_RECIPIENT so Resend's domain restriction is never hit.
    When TEST_RECIPIENT is empty, the real lead email is used — this requires
    a verified domain configured at resend.com/domains.
    """
    if SDR_OUTREACH_PROVIDER == "dry_run" or not to_email:
        ts = _utc_now_iso()
        print(f"[dry_run] Would send to {to_email} | subject={subject!r}")
        return {"status": "dry_run", "timestamp": ts, "error": ""}

    effective_to = TEST_RECIPIENT if TEST_RECIPIENT else to_email
    if TEST_RECIPIENT and TEST_RECIPIENT != to_email:
        print(f"[resend] ⚠️  test mode — redirecting {to_email} → {effective_to}")

    try:
        r = requests.post(
            RESEND_API_URL,
            headers={
                "Authorization": f"Bearer {RESEND_API_KEY}",
                "Content-Type":  "application/json",
            },
            json={
                "from":    f"{RESEND_SENDER_NAME} <{RESEND_FROM_EMAIL}>",
                "to":      [effective_to],
                "subject": subject,
                "text":    body,
            },
            timeout=30,
        )
        if r.ok:
            ts = _utc_now_iso()
            print(f"[resend] ✅ sent -> {effective_to} at {ts}")
            return {"status": "sent", "timestamp": ts, "error": ""}
        err = f"Resend error {r.status_code}: {r.text}"
        print(f"[resend] ❌ {err}")
        return {"status": "failed", "timestamp": _utc_now_iso(), "error": err}
    except Exception as exc:
        return {"status": "failed", "timestamp": _utc_now_iso(), "error": str(exc)}


# ---------------- storage ----------------
SCHEMA = """
CREATE TABLE IF NOT EXISTS campaigns (
    id TEXT PRIMARY KEY, lead_email TEXT, lead_name TEXT, company TEXT,
    subject TEXT, body TEXT, status TEXT, created_at TEXT, updated_at TEXT, send_error TEXT
);
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY, campaign_id TEXT, inbound_sender TEXT, inbound_subject TEXT,
    inbound_body TEXT, classification TEXT, confidence REAL, draft_subject TEXT,
    draft_body TEXT, status TEXT, created_at TEXT, updated_at TEXT, send_error TEXT
);
"""


@contextmanager
def get_conn():
    conn = sqlite3.connect(SDR_DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db():
    with get_conn() as conn:
        conn.executescript(SCHEMA)


def create_campaign(lead_email, lead_name, company, subject, body, status="pending_approval"):
    cid, ts = str(uuid.uuid4()), _utc_now_iso()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO campaigns VALUES (?,?,?,?,?,?,?,?,?,?)",
            (cid, lead_email, lead_name, company, subject, body, status, ts, ts, ""),
        )
    return get_campaign(cid)


def get_campaign(cid):
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM campaigns WHERE id=?", (cid,)).fetchone()
        return dict(row) if row else None


def update_campaign(cid, **fields):
    fields["updated_at"] = _utc_now_iso()
    set_clause = ", ".join(f"{k}=?" for k in fields)
    with get_conn() as conn:
        conn.execute(f"UPDATE campaigns SET {set_clause} WHERE id=?", (*fields.values(), cid))
    return get_campaign(cid)


def create_conversation(campaign_id, inbound_sender, inbound_subject, inbound_body,
                        classification, confidence, draft_subject, draft_body, status):
    conv_id, ts = str(uuid.uuid4()), _utc_now_iso()
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO conversations VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (conv_id, campaign_id, inbound_sender, inbound_subject, inbound_body,
             classification, confidence, draft_subject, draft_body, status, ts, ts, ""),
        )
    return get_conversation(conv_id)


def get_conversation(conv_id):
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM conversations WHERE id=?", (conv_id,)).fetchone()
        return dict(row) if row else None


def update_conversation(conv_id, **fields):
    fields["updated_at"] = _utc_now_iso()
    set_clause = ", ".join(f"{k}=?" for k in fields)
    with get_conn() as conn:
        conn.execute(f"UPDATE conversations SET {set_clause} WHERE id=?", (*fields.values(), conv_id))
    return get_conversation(conv_id)


# ---------------- outbound: Outreach Agent ----------------
OUTBOUND_SYSTEM_PROMPT = (
    "You are an SDR writing a first-touch cold outbound email. Be concise "
    "(under 150 words), specific to the lead's company and pain points, and "
    "end with a single low-friction call to action. No subject line in the body."
)


class OutboundState(TypedDict, total=False):
    lead_name: str; lead_email: str; company: str; persona: str
    pain_points: str; enrichment_notes: str; offer_summary: str
    draft_subject: str; draft_body: str


def _template_draft(state):
    name    = state.get("lead_name")    or "there"
    company = state.get("company")      or "your team"
    pain    = state.get("pain_points")  or "the challenges your team is navigating"
    offer   = state.get("offer_summary") or "how we help teams like yours"
    subject = f"Quick idea for {company}"
    body    = (
        f"Hi {name},\n\nNoticed {company} has been dealing with {pain}. "
        f"Wanted to share {offer} -- happy to send a 2-minute summary or "
        f"grab 15 minutes if useful.\n\nWorth a quick chat?\n\nBest,\nSDR Team"
    )
    return subject, body


def outbound_build_draft(state):
    user_prompt = (
        f"Lead name: {state.get('lead_name')}\nCompany: {state.get('company')}\n"
        f"Persona: {state.get('persona')}\nPain points: {state.get('pain_points')}\n"
        f"Enrichment notes: {state.get('enrichment_notes')}\n"
        f"Offer summary: {state.get('offer_summary')}\n\nWrite the email body only."
    )
    try:
        body    = llm_complete(OUTBOUND_SYSTEM_PROMPT, user_prompt)
        subject = f"Quick idea for {state.get('company') or 'your team'}"
        print("[outbound] generated via LLM")
        return {"draft_subject": subject, "draft_body": body}
    except LLMUnavailable as exc:
        print(f"[outbound] LLM unavailable ({exc}), using template.")
        subject, body = _template_draft(state)
        return {"draft_subject": subject, "draft_body": body}


def build_outbound_graph():
    g = StateGraph(OutboundState)
    g.add_node("build_draft", outbound_build_draft)
    g.add_edge(START, "build_draft")
    g.add_edge("build_draft", END)
    return g.compile()


def draft_campaign(lead: dict) -> dict:
    result = build_outbound_graph().invoke(lead)
    return {"draft_subject": result["draft_subject"], "draft_body": result["draft_body"]}


# ---------------- inbound: Conversation Agent ----------------
INBOUND_SYSTEM_PROMPT = (
    "You are an SDR replying to an inbound email from a prospect. Write a "
    "short, warm, professional reply appropriate to the classified intent. "
    "Keep it under 120 words."
)

_KEYWORDS = {
    "unsubscribe":    ["unsubscribe", "remove me", "stop emailing", "opt out", "opt-out"],
    "wrong_person":   ["wrong person", "not the right person", "doesn't handle", "not my area"],
    "out_of_office":  ["out of office", "ooo", "on leave", "back on", "vacation"],
    "meeting_request":["meeting", "call", "schedule", "calendar", "book a time", "available"],
    "pricing_request":["price", "pricing", "cost", "quote", "how much", "budget"],
    "objection":      ["not interested", "no budget", "already have", "not a priority", "not now"],
    "interested":     ["interested", "tell me more", "sounds good", "sounds great", "let's talk"],
}


class InboundState(TypedDict, total=False):
    sender: str; subject: str; body: str; normalized_body: str
    classification: str; confidence: float
    draft_subject: str; draft_body: str
    status: Literal["awaiting_approval", "human_review"]


def inbound_read_reply(state):
    return {"normalized_body": re.sub(r"\s+", " ", (state.get("body") or "").strip())}


def inbound_classify_intent(state):
    haystack = f"{(state.get('normalized_body') or '').lower()} {(state.get('subject') or '').lower()}"
    scores = {k: 0.0 for k in _KEYWORDS}
    for label, terms in _KEYWORDS.items():
        for t in terms:
            if t in haystack:
                scores[label] += 1.0
    if "not now" in haystack or "not right now" in haystack:
        scores["objection"] -= 0.5
        scores["not_now"] = scores.get("not_now", 0.0) + 1.5
    best_label, raw = max(scores.items(), key=lambda kv: kv[1])
    if raw <= 0:
        return {"classification": "ambiguous", "confidence": 0.35}
    return {"classification": best_label, "confidence": min(0.95, 0.5 + 0.15 * raw)}


def inbound_route_after_classify(state):
    return "human_review" if (state.get("confidence") or 0.0) < CONFIDENCE_THRESHOLD else "draft_reply"


def _template_inbound_reply(state):
    classification = state.get("classification") or "ambiguous"
    subj = state.get("subject") or "Your message"
    name = (state.get("sender") or "there").split("@", 1)[0].replace(".", " ").title()
    bodies = {
        "meeting_request": f"Hi {name},\n\nHappy to find time -- sharing a scheduling link shortly.\n\nBest,\nSDR Team",
        "pricing_request": f"Hi {name},\n\nThanks for asking -- a teammate will follow up with pricing shortly.\n\nBest,\nSDR Team",
        "objection":       f"Hi {name},\n\nTotally understand, happy to check back another time.\n\nBest,\nSDR Team",
        "not_now":         f"Hi {name},\n\nNo problem -- I'll follow up another time.\n\nBest,\nSDR Team",
        "unsubscribe":     f"Hi {name},\n\nConfirmed -- you won't hear from us again.\n\nBest,\nSDR Team",
        "wrong_person":    f"Hi {name},\n\nThanks for letting me know -- could you point me to the right person?\n\nBest,\nSDR Team",
        "out_of_office":   f"Hi {name},\n\nNo worries -- I'll follow up once you're back.\n\nBest,\nSDR Team",
        "interested":      f"Hi {name},\n\nGreat to hear! Sharing more details shortly.\n\nBest,\nSDR Team",
        "ambiguous":       f"Hi {name},\n\nThanks for the reply -- could you share a bit more on what you're looking for?\n\nBest,\nSDR Team",
    }
    reply_subj = f"Re: {subj}" if not subj.lower().startswith("re:") else subj
    return reply_subj, bodies.get(classification, bodies["ambiguous"])


def inbound_draft_reply(state):
    subj       = state.get("subject") or "Your message"
    reply_subj = f"Re: {subj}" if not subj.lower().startswith("re:") else subj
    user_prompt = (
        f"Sender: {state.get('sender')}\nSubject: {subj}\nBody: {state.get('normalized_body')}\n"
        f"Classified intent: {state.get('classification')} "
        f"(confidence {state.get('confidence', 0):.2f})"
    )
    try:
        body = llm_complete(INBOUND_SYSTEM_PROMPT, user_prompt)
        print("[inbound] generated via LLM")
        return {"draft_subject": reply_subj, "draft_body": body, "status": "awaiting_approval"}
    except LLMUnavailable as exc:
        print(f"[inbound] LLM unavailable ({exc}), using template.")
        s, b = _template_inbound_reply(state)
        return {"draft_subject": s, "draft_body": b, "status": "awaiting_approval"}


def inbound_human_review(state):
    print(f"[inbound] Low confidence ({state.get('confidence', 0):.2f}) -- flagged for review.")
    return {"status": "human_review", "draft_subject": "", "draft_body": ""}


def build_inbound_graph():
    g = StateGraph(InboundState)
    g.add_node("read_reply",       inbound_read_reply)
    g.add_node("classify_intent",  inbound_classify_intent)
    g.add_node("draft_reply",      inbound_draft_reply)
    g.add_node("human_review",     inbound_human_review)
    g.add_edge(START, "read_reply")
    g.add_edge("read_reply", "classify_intent")
    g.add_conditional_edges(
        "classify_intent", inbound_route_after_classify,
        {"draft_reply": "draft_reply", "human_review": "human_review"},
    )
    g.add_edge("draft_reply",  END)
    g.add_edge("human_review", END)
    return g.compile()


def classify_and_draft(sender, subject, body):
    result = build_inbound_graph().invoke({"sender": sender, "subject": subject, "body": body})
    return {
        "classification": result.get("classification"),
        "confidence":     result.get("confidence"),
        "draft_subject":  result.get("draft_subject", ""),
        "draft_body":     result.get("draft_body", ""),
        "status":         result.get("status", "awaiting_approval"),
    }


# ---------------- demo ----------------
def run_demo():
    init_db()

    # ── Print config summary ────────────────────────────────────────────────
    llm_mode    = "Groq LLM" if GROQ_API_KEY   else "template fallback"
    email_mode  = "resend"   if RESEND_API_KEY  else "dry_run"
    routing_msg = f"→ {TEST_RECIPIENT} (test redirect)" if TEST_RECIPIENT else "→ real lead email (needs verified domain)"
    print(f"\n📋 Config: LLM={llm_mode} | email={email_mode} {routing_msg}\n")

    print("=== OUTBOUND: Outreach Agent ===")
    lead = {
        "lead_name":        "Jane Doe",
        "lead_email":       "jane.doe@acmerobotics.com",   # real CRM value; redirected in test mode
        "company":          "Acme Robotics",
        "persona":          "VP of Sales",
        "pain_points":      "slow manual lead qualification and a growing SDR backlog",
        "enrichment_notes": "Acme Robotics raised a Series B 3 months ago and is hiring 4 SDRs.",
        "offer_summary":    "an AI SDR pipeline that qualifies and personalizes outreach automatically",
    }

    draft    = draft_campaign(lead)
    campaign = create_campaign(
        lead["lead_email"], lead["lead_name"], lead["company"],
        draft["draft_subject"], draft["draft_body"],
    )
    print(f"Campaign {campaign['id']} status={campaign['status']}")
    print(f"Subject: {campaign['subject']}\n{campaign['body']}\n")

    print("-- approving + sending campaign --")
    campaign = update_campaign(campaign["id"], status="approved")
    result   = send_email(campaign["lead_email"], campaign["subject"], campaign["body"])
    send_status = "sent" if result["status"] in ("sent", "dry_run") else "failed"
    campaign = update_campaign(campaign["id"], status=send_status, send_error=result.get("error", ""))
    print(f"Campaign status={campaign['status']}\n")

    print("=== INBOUND: Conversation Agent ===")
    update_campaign(campaign["id"], status="stopped")

    inbound_subject = f"Re: {campaign['subject']}"
    inbound_body    = "Thanks for reaching out -- this looks interesting, can we set up a call next week?"
    inbound         = classify_and_draft(lead["lead_email"], inbound_subject, inbound_body)
    conversation    = create_conversation(
        campaign["id"], lead["lead_email"], inbound_subject, inbound_body,
        inbound["classification"], inbound["confidence"],
        inbound["draft_subject"], inbound["draft_body"], inbound["status"],
    )
    print(
        f"Classification={conversation['classification']} "
        f"(confidence={conversation['confidence']:.2f}), "
        f"status={conversation['status']}"
    )
    print(f"Draft reply: {conversation['draft_subject']}\n{conversation['draft_body']}\n")

    if conversation["draft_body"]:
        print("-- approving + sending reply --")
        conversation = update_conversation(conversation["id"], status="approved")
        result       = send_email(
            conversation["inbound_sender"],
            conversation["draft_subject"],
            conversation["draft_body"],
        )
        send_status  = "sent" if result["status"] in ("sent", "dry_run") else "failed"
        conversation = update_conversation(
            conversation["id"], status=send_status, send_error=result.get("error", ""),
        )
        print(f"Conversation status={conversation['status']}")

    print(f"\n=== DONE. Stored in {SDR_DATABASE_PATH} ===")


print("✅ SDR pipeline loaded.")
run_demo()