# -*- coding: utf-8 -*-
"""SMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHb7X_ta5VnpTplvrumxXM7iUygV3x-e
"""

!pip install twilio python-dotenv

import os
from dataclasses import dataclass
from typing import Optional

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from twilio.rest import Client
from twilio.base.exceptions import TwilioRestException


@dataclass
class SMSMessage:
    to_number: str
    body: str
    from_number: Optional[str] = None  # falls back to TWILIO_FROM_NUMBER if omitted


@dataclass
class SMSResult:
    success: bool
    sid: Optional[str] = None
    status: Optional[str] = None
    error: Optional[str] = None


def _get_client() -> Client:
    account_sid = os.environ.get("TWILIO_ACCOUNT_SID")
    if not account_sid:
        raise RuntimeError("TWILIO_ACCOUNT_SID is not set.")

    api_key_sid = os.environ.get("TWILIO_API_KEY_SID")
    api_key_secret = os.environ.get("TWILIO_API_KEY_SECRET")
    if api_key_sid and api_key_secret:
        return Client(api_key_sid, api_key_secret, account_sid)

    auth_token = os.environ.get("TWILIO_AUTH_TOKEN")
    if auth_token:
        return Client(account_sid, auth_token)

    raise RuntimeError(
        "Missing Twilio credentials: set TWILIO_API_KEY_SID + "
        "TWILIO_API_KEY_SECRET (recommended) or TWILIO_AUTH_TOKEN, "
        "alongside TWILIO_ACCOUNT_SID."
    )


def send_sms(message: SMSMessage) -> SMSResult:
    from_number = message.from_number or os.environ.get("TWILIO_FROM_NUMBER")
    if not from_number:
        return SMSResult(success=False, error="No from_number given and TWILIO_FROM_NUMBER is not set.")

    try:
        client = _get_client()
    except RuntimeError as e:
        return SMSResult(success=False, error=str(e))

    try:
        twilio_message = client.messages.create(
            to=message.to_number,
            from_=from_number,
            body=message.body,
        )
        return SMSResult(success=True, sid=twilio_message.sid, status=twilio_message.status)
    except TwilioRestException as e:
        return SMSResult(success=False, error=f"Twilio error {e.code}: {e.msg}")
    except Exception as e:
        return SMSResult(success=False, error=f"Unexpected error: {e}")


# ---------------------------------------------------------------------------
# Fill these in, then run.
# ---------------------------------------------------------------------------
os.environ["TWILIO_ACCOUNT_SID"] = "SK83292b1b7dd5dc36d693bdf9b4d80788"  # console.twilio.com
os.environ["TWILIO_AUTH_TOKEN"] = "1081bcdffd598256569816d1eb9c1a00"
os.environ["TWILIO_FROM_NUMBER"] = "+91-9348632610"          # your Twilio number

result = send_sms(SMSMessage(
    to_number="+1(774)433-0370",   # <- recipient's number, E.164 format
    body="Hello from Twilio!",
))

print(result)
if result.success:
    print(f"Sent! SID={result.sid}, status={result.status}")
else:
    print(f"Failed: {result.error}")